# fly.toml app configuration file generated for tw-stock-mcp on 2026-04-23T17:50:54+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tw-stock-mcp'
primary_region = 'nrt'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 250
    soft_limit = 200

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
